# Generated by Django 5.2.7 on 2026-06-14 15:32

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Caption/description for this day', max_length=500)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('is_video', models.BooleanField(default=False)),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('day_number_field', models.PositiveIntegerField(db_index=True, default=1)),
                ('actual_date', models.DateField(blank=True, help_text='When this milestone actually happened (e.g., project completion date)', null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, help_text='Original social media URL')),
                ('source_platform', models.CharField(blank=True, help_text='tiktok, youtube, instagram, facebook', max_length=20)),
                ('embed_html', models.TextField(blank=True, help_text='Embed HTML for social media content')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['day_number_field'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('creators', 'For Creators'), ('supporters', 'For Supporters'), ('payments', 'Payments')], default='general', max_length=20)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('fitness', 'Fitness & Wellness'), ('learning', 'Learning & Skills'), ('creative', 'Creative Projects'), ('business', 'Business & Startups'), ('personal', 'Personal Growth'), ('cause', 'Social Cause'), ('other', 'Other')], default='personal', max_length=20)),
                ('journey_type', models.CharField(choices=[('daily', 'Daily Challenge'), ('milestone', 'Milestone Journey')], default='daily', max_length=20)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('cover_video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Number of days or milestones')),
                ('duration_unit', models.CharField(default='days', max_length=10)),
                ('current_day_override', models.PositiveIntegerField(blank=True, help_text='Manually set current day for creators already in progress. Overrides calendar calculation.', null=True)),
                ('milestones', models.JSONField(blank=True, default=list, help_text='List of milestone descriptions')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('auto_import_enabled', models.BooleanField(default=False)),
                ('import_hashtag', models.CharField(blank=True, max_length=50)),
                ('funding_enabled', models.BooleanField(default=False)),
                ('funding_goal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('funding_description', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('total_watch_time', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('template_style', models.CharField(default='default', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Journeys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('fitness', 'Fitness & Wellness'), ('learning', 'Learning & Skills'), ('creative', 'Creative Projects'), ('business', 'Business & Startups'), ('personal', 'Personal Growth'), ('cause', 'Social Cause'), ('other', 'Other')], max_length=20)),
                ('journey_type', models.CharField(choices=[('daily', 'Daily Challenge'), ('milestone', 'Milestone Journey')], default='daily', max_length=20)),
                ('duration', models.PositiveIntegerField(default=30)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('template_style', models.CharField(choices=[('default', 'Default'), ('fitness', 'Fitness'), ('portfolio', 'Portfolio'), ('startup', 'Startup')], default='default', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('is_free', models.BooleanField(default=False)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General Question'), ('support', 'Technical Support'), ('fundraising', 'Fundraising Question'), ('journey', 'Journey Help'), ('import', 'Content Import Issue')], max_length=50)),
                ('message', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('platform_post_id', models.CharField(max_length=100)),
                ('platform_url', models.URLField(max_length=500)),
                ('caption', models.TextField()),
                ('media_url', models.URLField(max_length=500)),
                ('media_type', models.CharField(max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('posted_at', models.DateTimeField()),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('detected_day', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_day', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('assigned', 'Assigned to Day'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.activity')),
                ('assigned_journey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_content', to='main.journey')),
            ],
            options={
                'verbose_name_plural': 'Imported Content',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='imported_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.importedcontent'),
        ),
        migrations.AddField(
            model_name='activity',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.journey'),
        ),
        migrations.CreateModel(
            name='JourneyFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('notify_on_activity', models.BooleanField(default=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_journeys', through='main.JourneyFollow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JourneySave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('redirect_link', models.URLField(blank=True)),
                ('viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostJourneyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('blueprint', 'Blueprint PDF'), ('behind_scenes', 'Behind the Scenes Video'), ('coaching', 'One-on-One Coaching'), ('bundle', 'Complete Bundle')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pdf_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf')),
                ('video_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('coaching_calendar_link', models.URLField(blank=True)),
                ('coaching_duration', models.IntegerField(default=60, help_text='Minutes per session')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_journey_products', to='main.journey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='v1763637368/pp_vvzbcj', max_length=255, verbose_name='image')),
                ('bio', models.TextField(default='No bio available', max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('tiktok_username', models.CharField(blank=True, max_length=50)),
                ('instagram_username', models.CharField(blank=True, max_length=50)),
                ('youtube_channel', models.CharField(blank=True, max_length=100)),
                ('profile_verified', models.BooleanField(default=False)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='main.profile'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('copyright', 'Copyright Violation'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.activity')),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.journey')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('copy', 'Copy Link'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='main.journey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
            },
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=20)),
                ('platform_user_id', models.CharField(max_length=100)),
                ('platform_username', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires', models.DateTimeField(null=True)),
                ('auto_import', models.BooleanField(default=True)),
                ('import_hashtag', models.CharField(blank=True, max_length=50)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='importedcontent',
            name='social_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_content', to='main.socialconnection'),
        ),
        migrations.CreateModel(
            name='JourneyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.journey')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='journeys', through='main.JourneyTag', to='main.tag'),
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity', '-created_at'], name='main_activi_activit_262193_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loves', to='main.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['activity', '-created_at'], name='main_activi_activit_18b5d4_idx')],
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=100)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paypal_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='main.journey')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['journey', 'status'], name='main_donati_journey_1824d7_idx'), models.Index(fields=['donor', '-created_at'], name='main_donati_donor_i_ff3134_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['journey', 'day_number_field'], name='main_activi_journey_0d69f1_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['journey', 'created_at'], name='main_activi_journey_b91b59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('journey', 'day_number_field')},
        ),
        migrations.AddIndex(
            model_name='journeyfollow',
            index=models.Index(fields=['user', '-followed_at'], name='main_journe_user_id_0b635d_idx'),
        ),
        migrations.AddIndex(
            model_name='journeyfollow',
            index=models.Index(fields=['journey', '-followed_at'], name='main_journe_journey_8932f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journeyfollow',
            unique_together={('user', 'journey')},
        ),
        migrations.AddIndex(
            model_name='journeysave',
            index=models.Index(fields=['journey', '-saved_at'], name='main_journe_journey_930438_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journeysave',
            unique_together={('user', 'journey')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'viewed'], name='main_notifi_user_id_bf5b05_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='main_notifi_user_id_4211ba_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='main_profil_user_id_a55cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['journey', '-created_at'], name='main_share_journey_8bcbbe_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconnection',
            index=models.Index(fields=['user', 'platform'], name='main_social_user_id_e24f45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialconnection',
            unique_together={('user', 'platform')},
        ),
        migrations.AddIndex(
            model_name='importedcontent',
            index=models.Index(fields=['social_connection', 'status'], name='main_import_social__c3ea54_idx'),
        ),
        migrations.AddIndex(
            model_name='importedcontent',
            index=models.Index(fields=['assigned_journey', 'assigned_day'], name='main_import_assigne_6e13b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importedcontent',
            unique_together={('platform', 'platform_post_id')},
        ),
        migrations.AlterUniqueTogether(
            name='journeytag',
            unique_together={('journey', 'tag')},
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['creator', '-created_at'], name='main_journe_creator_fd7d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['category', 'is_public'], name='main_journe_categor_370bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['slug'], name='main_journe_slug_1e91a7_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['is_featured', '-created_at'], name='main_journe_is_feat_16d160_idx'),
        ),
    ]
