# Generated by Django 5.2.7 on 2026-07-16 08:09

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('wellness', 'Wellness')], default='fitness', max_length=20)),
                ('journey_type', models.CharField(choices=[('daily', 'Daily Journey')], default='daily', max_length=20)),
                ('fitness_goal', models.CharField(blank=True, choices=[('build_muscle', 'Build Muscle'), ('lose_weight', 'Lose Weight'), ('increase_stamina', 'Increase Stamina'), ('improve_flexibility', 'Improve Flexibility'), ('run_faster', 'Run Faster'), ('general_fitness', 'General Fitness')], help_text="What's your main fitness goal?", max_length=50, null=True)),
                ('wellness_focus', models.CharField(blank=True, choices=[('mental_health', 'Mental Health'), ('better_sleep', 'Better Sleep'), ('stress_reduction', 'Stress Reduction'), ('mindfulness', 'Mindfulness'), ('nutrition', 'Nutrition'), ('general_wellness', 'General Wellness')], help_text="What's your wellness focus?", max_length=50, null=True)),
                ('custom_goal', models.CharField(blank=True, help_text='Custom goal if none of the above fit', max_length=200)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('template_style', models.CharField(choices=[('fitness', 'Fitness')], default='fitness', help_text='Display style for your journey', max_length=20)),
                ('duration', models.PositiveIntegerField(default=30, help_text='Number of days for this fitness/wellness journey')),
                ('current_day_override', models.PositiveIntegerField(blank=True, help_text='Manually set current day. Overrides calendar calculation.', null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('privacy_status', models.CharField(choices=[('private', 'Private — Only Me'), ('unlisted', 'Unlisted — Anyone with Link'), ('public', 'Public — Everyone')], default='private', max_length=20)),
                ('allow_comments', models.BooleanField(default=False, help_text='Allow public comments')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False, help_text='Journey is complete and archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Journeys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General Question'), ('support', 'Technical Support'), ('journey', 'Journey Help'), ('export', 'Export Help'), ('feature', 'Feature Request')], default='general', max_length=50)),
                ('message', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for this entry', max_length=200)),
                ('content', models.TextField(help_text='Your entry content', max_length=500)),
                ('summary', models.TextField(blank=True, help_text='Short summary')),
                ('activity_type', models.CharField(blank=True, choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('hiit', 'HIIT'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('walking', 'Walking'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('sports', 'Sports'), ('stretching', 'Stretching'), ('other', 'Other')], help_text='Type of activity', max_length=20, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('intensity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Intensity level', max_length=10, null=True)),
                ('media_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('is_video', models.BooleanField(default=False)),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('media_caption', models.CharField(blank=True, max_length=200)),
                ('day_number_field', models.PositiveIntegerField(db_index=True, default=1)),
                ('actual_date', models.DateField(blank=True, help_text='Actual date of the entry', null=True)),
                ('mood', models.CharField(blank=True, choices=[('amazing', '🌟 Amazing'), ('great', '💪 Great'), ('good', '👍 Good'), ('okay', '😐 Okay'), ('tired', '😴 Tired'), ('challenged', '💪 Challenged'), ('struggling', '😞 Struggling'), ('proud', '🏆 Proud'), ('grateful', '🙏 Grateful'), ('neutral', '😶 Neutral')], max_length=20, null=True)),
                ('progress_metrics', models.JSONField(blank=True, default=dict)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.journey')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['day_number_field'],
            },
        ),
        migrations.CreateModel(
            name='JourneyFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_new_entry', models.BooleanField(default=True)),
                ('notify_on_completion', models.BooleanField(default=True)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JourneySave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'New Comment'), ('follow', 'New Follower'), ('milestone', 'Milestone Reached'), ('export', 'Export Ready')], default='comment', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('redirect_link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.activity')),
                ('related_journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='v1763637368/pp_vvzbcj', max_length=255, verbose_name='image')),
                ('bio', models.TextField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='main.profile'),
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection_type', models.CharField(choices=[('workout', 'Workout Reflection'), ('nutrition', 'Nutrition Reflection'), ('mental', 'Mental Wellness'), ('recovery', 'Recovery & Sleep'), ('milestone', 'Milestone Celebration'), ('struggle', 'Struggle / Challenge'), ('gratitude', 'Gratitude'), ('general', 'General Reflection')], default='general', max_length=20)),
                ('summary', models.CharField(help_text='What was this reflection about?', max_length=100)),
                ('reflection', models.TextField(help_text='How did you feel? What did you learn?', max_length=500)),
                ('mood', models.CharField(blank=True, choices=[('amazing', '🌟 Amazing'), ('good', '👍 Good'), ('okay', '😐 Okay'), ('tired', '😴 Tired'), ('challenged', '💪 Challenged'), ('struggling', '😞 Struggling'), ('proud', '🏆 Proud'), ('grateful', '🙏 Grateful')], max_length=20, null=True)),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, help_text='1-10', null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_private', models.BooleanField(default=True, help_text='Private reflections stay between you and your journey')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='main.activity')),
                ('related_journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reflections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook')], max_length=20)),
                ('share_text', models.TextField()),
                ('share_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('publish_url', models.URLField(blank=True)),
                ('publish_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_publishes', to='main.activity')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_publishes', to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_publishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.journey')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('markdown', 'Markdown'), ('json', 'JSON'), ('html', 'HTML')], max_length=20)),
                ('include_media', models.BooleanField(default=True)),
                ('include_comments', models.BooleanField(default=False)),
                ('include_reflections', models.BooleanField(default=True)),
                ('file_url', models.URLField(blank=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='main.journey')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='main_export_user_id_6cf057_idx'), models.Index(fields=['journey', 'status'], name='main_export_journey_b70f53_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.journey')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['journey', '-created_at'], name='main_commen_journey_b62a01_idx'), models.Index(fields=['activity', '-created_at'], name='main_commen_activit_3a4318_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['journey', 'day_number_field'], name='main_activi_journey_0d69f1_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['journey', 'created_at'], name='main_activi_journey_b91b59_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='main_activi_activit_21638c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('journey', 'day_number_field')},
        ),
        migrations.AddIndex(
            model_name='journeyfollow',
            index=models.Index(fields=['user', '-followed_at'], name='main_journe_user_id_0b635d_idx'),
        ),
        migrations.AddIndex(
            model_name='journeyfollow',
            index=models.Index(fields=['journey', '-followed_at'], name='main_journe_journey_8932f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journeyfollow',
            unique_together={('user', 'journey')},
        ),
        migrations.AddIndex(
            model_name='journeysave',
            index=models.Index(fields=['journey', '-saved_at'], name='main_journe_journey_930438_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journeysave',
            unique_together={('user', 'journey')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='main_notifi_user_id_844422_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='main_notifi_user_id_4211ba_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='main_profil_user_id_a55cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['creator', '-created_at'], name='main_journe_creator_fd7d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['category', 'privacy_status'], name='main_journe_categor_a32c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['slug'], name='main_journe_slug_1e91a7_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['is_featured', '-created_at'], name='main_journe_is_feat_16d160_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['user', '-created_at'], name='main_reflec_user_id_423115_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['user', 'related_journey'], name='main_reflec_user_id_62dfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['reflection_type'], name='main_reflec_reflect_423fac_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpublish',
            index=models.Index(fields=['user', 'status'], name='main_social_user_id_00fa3c_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpublish',
            index=models.Index(fields=['journey', 'status'], name='main_social_journey_4c52e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journeytag',
            unique_together={('journey', 'tag')},
        ),
    ]
