# Generated by Django 5.2.7 on 2026-07-03 14:43

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('fitness', 'Fitness & Wellness'), ('learning', 'Learning & Skills'), ('creative', 'Creative Projects'), ('business', 'Business & Startups'), ('personal', 'Personal Growth'), ('cause', 'Social Cause'), ('other', 'Other')], default='personal', max_length=20)),
                ('journey_type', models.CharField(choices=[('daily', 'Daily Journey'), ('milestone', 'Milestone Journey')], default='daily', max_length=20)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Number of days or milestones')),
                ('current_day_override', models.PositiveIntegerField(blank=True, help_text='Manually set current day. Overrides calendar calculation.', null=True)),
                ('milestones', models.JSONField(blank=True, default=list, help_text='List of milestone descriptions')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('privacy_status', models.CharField(choices=[('private', 'Private — Only Me'), ('unlisted', 'Unlisted — Anyone with Link'), ('public', 'Public — Everyone')], default='private', max_length=20)),
                ('allow_comments', models.BooleanField(default=False, help_text='Allow public comments')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False, help_text='Journey is complete and archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Journeys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for this entry', max_length=200)),
                ('content', models.TextField(help_text='Your entry content', max_length=500)),
                ('summary', models.TextField(blank=True, help_text='Short summary')),
                ('media_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('is_video', models.BooleanField(default=False)),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('media_caption', models.CharField(blank=True, max_length=200)),
                ('day_number_field', models.PositiveIntegerField(db_index=True, default=1)),
                ('actual_date', models.DateField(blank=True, help_text='Actual date of the entry', null=True)),
                ('mood', models.CharField(blank=True, choices=[('excited', 'Excited'), ('motivated', 'Motivated'), ('challenged', 'Challenged'), ('proud', 'Proud'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('unsure', 'Unsure'), ('accomplished', 'Accomplished'), ('struggling', 'Struggling'), ('grateful', 'Grateful')], max_length=20, null=True)),
                ('progress_metrics', models.JSONField(blank=True, default=dict)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.journey')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['day_number_field'],
            },
        ),
        migrations.CreateModel(
            name='JourneyFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_new_entry', models.BooleanField(default=True)),
                ('notify_on_completion', models.BooleanField(default=True)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JourneySave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'New Comment'), ('follow', 'New Follower'), ('milestone', 'Milestone Reached'), ('export', 'Export Ready')], default='comment', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('redirect_link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.activity')),
                ('related_journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='v1763637368/pp_vvzbcj', max_length=255, verbose_name='image')),
                ('bio', models.TextField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='main.profile'),
        ),
        migrations.CreateModel(
            name='SocialPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook')], max_length=20)),
                ('share_text', models.TextField()),
                ('share_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('publish_url', models.URLField(blank=True)),
                ('publish_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_publishes', to='main.activity')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_publishes', to='main.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_publishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.journey')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('media_files', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_private', models.BooleanField(default=True)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='main.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('related_journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='main.journey')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='main_journa_user_id_78cd96_idx'), models.Index(fields=['user', 'related_journey'], name='main_journa_user_id_e2565c_idx'), models.Index(fields=['user', 'is_private'], name='main_journa_user_id_63e3ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('markdown', 'Markdown'), ('json', 'JSON'), ('html', 'HTML')], max_length=20)),
                ('include_media', models.BooleanField(default=True)),
                ('include_comments', models.BooleanField(default=False)),
                ('file_url', models.URLField(blank=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='main.journey')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='main_export_user_id_6cf057_idx'), models.Index(fields=['journey', 'status'], name='main_export_journey_b70f53_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.journey')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['journey', '-created_at'], name='main_commen_journey_b62a01_idx'), models.Index(fields=['activity', '-created_at'], name='main_commen_activit_3a4318_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['journey', 'day_number_field'], name='main_activi_journey_0d69f1_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['journey', 'created_at'], name='main_activi_journey_b91b59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('journey', 'day_number_field')},
        ),
        migrations.AddIndex(
            model_name='journeyfollow',
            index=models.Index(fields=['user', '-followed_at'], name='main_journe_user_id_0b635d_idx'),
        ),
        migrations.AddIndex(
            model_name='journeyfollow',
            index=models.Index(fields=['journey', '-followed_at'], name='main_journe_journey_8932f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journeyfollow',
            unique_together={('user', 'journey')},
        ),
        migrations.AddIndex(
            model_name='journeysave',
            index=models.Index(fields=['journey', '-saved_at'], name='main_journe_journey_930438_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journeysave',
            unique_together={('user', 'journey')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='main_notifi_user_id_844422_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='main_notifi_user_id_4211ba_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='main_profil_user_id_a55cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['creator', '-created_at'], name='main_journe_creator_fd7d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['category', 'privacy_status'], name='main_journe_categor_a32c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['slug'], name='main_journe_slug_1e91a7_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['is_featured', '-created_at'], name='main_journe_is_feat_16d160_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpublish',
            index=models.Index(fields=['user', 'status'], name='main_social_user_id_00fa3c_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpublish',
            index=models.Index(fields=['journey', 'status'], name='main_social_journey_4c52e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journeytag',
            unique_together={('journey', 'tag')},
        ),
    ]
